export SHELL_HOME=~/dotfiles/shells
source "$SHELL_HOME/alias"
source "$SHELL_HOME/env"
source "$SHELL_HOME/zsh/config.zsh"

local smiley="%(?,%{$fg[green]%}☺%{$reset_color%},%{$fg[red]%}☹%{$reset_color%})"
PROMPT='
%~
${smiley}  %{$reset_color%}'

RPROMPT='%{$fg[white]%} $(date "+%H:%M:%S")%{$reset_color%}'

