export SHELL_HOME=~/dotfiles/shells

source "$SHELL_HOME/alias"

export PATH=~/bin:/usr/local/bin:$PATH

autoload -U colors
colors
setopt prompt_subst

local smiley="%(?,%{$fg[green]%}☺%{$reset_color%},%{$fg[red]%}☹%{$reset_color%})"
PROMPT='
%~
${smiley}  %{$reset_color%}'

RPROMPT='%{$fg[white]%} $(date "+%H:%M:%S")%{$reset_color%}'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
