set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Bundle 'gmarik/vundle'

Bundle 'altercation/vim-colors-solarized'
Bundle 'tpope/vim-surround'
Bundle 'kien/ctrlp.vim'
Bundle 'VimClojure'
Bundle 'puppetlabs/puppet-syntax-vim'

"call pathogen#infect()
"call pathogen#helptags()
filetype plugin indent on
syntax on

"I cant spel
setlocal spell spelllang=en_ca

set number

set hlsearch
set incsearch

set undolevels=3000
set cindent

set nowrap
set smartindent tabstop=2 shiftwidth=2 expandtab

set wildmode=list:full,list:longest
set wildignore+=*.swp,*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'

set showcmd

"Clojure
let vimclojure#HighlightBuiltins=1
let vimclojure#DynamicHighlighting=1
let vimclojure#ParenRainbow=1
let vimclojure#WantNailgun=1

"Ctrlp
let g:ctrlp_arg_map = 1

"Stylin
set background=light
"let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contract="high"
let g:solarized_visibility="high"
colorscheme solarized 

"Key mappin
let mapleader = ","
let maplocalleader = "."

map <F2> :NERDTreeToggle<CR>
map <F3> :noh<CR>
let NERDTreeChDirMode=2

map <C-f><C-b> :FufBuffer<CR>
map <C-f><C-f> :FufFile<CR>
