call pathogen#infect()
call pathogen#helptags()
syntax on
filetype plugin indent on

"I cant spel
setlocal spell spelllang=en_ca

set hlsearch
set incsearch

set undolevels=3000
set cindent

set nowrap
set smartindent tabstop=2 shiftwidth=2 expandtab

set wildmode=list:full,list:longest
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

set showcmd

"Clojure
let vimclojure#WantNailgun=1

"Stylin
set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contract="high"
let g:solarized_visibility="high"
colorscheme solarized 

"Key mappin
let mapleader = ","

map <F2> :NERDTreeToggle<CR>
map <F3> :noh<CR>
let NERDTreeChDirMode=2

map <C-f><C-b> :FufBuffer<CR>
map <C-f><C-f> :FufFile<CR>

map <C-n> :set number<CR>
map <C-n><C-n> :set nonumber<CR>
