set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Bundle 'gmarik/vundle'

Bundle 'sjl/badwolf'
Bundle 'tpope/vim-fugitive'
Bundle 'kien/ctrlp.vim'
Bundle 'VimClojure'
Bundle 'scrooloose/nerdtree'
Bundle "pangloss/vim-javascript"

filetype plugin indent on
syntax on

"I cant spel
"setlocal spell spelllang=en_ca

set noswapfile

set number

set hlsearch
set incsearch

set undolevels=3000
"set cindent

set nowrap
set smartindent tabstop=2 shiftwidth=2 expandtab

set wildmode=list:full,list:longest
set wildignore+=*.swp,*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

map <Up> 
map <Down> 
map <Left> <Nop>
map <Right> <Nop>

imap <Up>     <Nop>
imap <Down>   <Nop>
imap <Left>   <Nop>
imap <Right>  <Nop>

map j gj
map k gk

map <space> .ef
map K :call vimclojure#DocLookup(expand("<cword>"))<CR>


set showcmd

"Clojure
let vimclojure#HighlightBuiltins=1
let vimclojure#DynamicHighlighting=1
let vimclojure#ParenRainbow=1
let vimclojure#WantNailgun=1
let vimclojure#SplitPos = "right"
let vimclojure#SplitSize = 80

"Ctrlp
let g:ctrlp_arg_map = 1
let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'

"Stylin
set background=dark
color badwolf

"Key mappin
let mapleader = ","
let maplocalleader = "."

map <F3> :noh<CR>
map <F2> :NERDTree<CR>
map <F2> :NERDTree<CR>
